# Kalshi Market Data Collection

Collects Kalshi prediction-market prices for every 2025–26 NBA regular-season game at four checkpoints: pre-game and the end of quarters 1–3. Builds a one-row-per-game table from the full-game box scores produced by `nba_stats_data.ipynb`, pulls the exact start time of each quarter from the NBA play-by-play API, builds the Kalshi market ticker for each team, and fetches the last market candlestick before each checkpoint. The outputs are loaded by `data_prep.ipynb`.

**Checkpoints:** each checkpoint is defined by the start of the next quarter, so prices reflect what the market knew at that moment.

| Checkpoint | Snapshot time |
|---|---|
| Pre-game | Start of Q1 (tip-off) |
| End of Q1 | Start of Q2 |
| End of Q2 | Start of Q3 |
| End of Q3 | Start of Q4 |

**Output files** (saved to `data/`, one per checkpoint):

| File | Contents |
|---|---|
| `main(_pre-game).csv`, `main(EndQ1).csv`, `main(EndQ2).csv`, `main(EndQ3).csv` | One row per game: game ID, date, quarter start time and Unix timestamp, home and away Kalshi tickers, team names, final score, and winner |
| `kalshi(_pre-game).csv`, `kalshi(EndQ1).csv`, `kalshi(EndQ2).csv`, `kalshi(EndQ3).csv` | One row per Kalshi market (two per game, one for each team): the last 1-minute candlestick before the snapshot time, with bid/ask prices, volume, and open interest |

## 1. Setup

Imports libraries and defines the constants used throughout the notebook: the season, the delay between API requests (to stay under rate limits), the Kalshi API base URL, and the path to the full-game box-score file produced by `nba_stats_data.ipynb`.

In [ ]:
import time
import requests
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import playbyplayv3

pd.set_option('display.max_columns', None)

SEASON = "2025-26"
REQUEST_DELAY_SECONDS = 0.5
BASE_URL = "https://external-api.kalshi.com/trade-api/v2"
DATA = "../data/_team-box-stats(full-game).csv"

## 2. Helper Functions

Functions used by the steps that follow:

- **`game_consolidation`**: collapses the box-score file (two rows per game, one per team) into one row per game. The home team is the one whose `MATCHUP` contains `vs.` and the away team is the one with `@`.
- **`pull_quarter_start_times`**: reads each game's play-by-play log and extracts the wall-clock start time of a given quarter (for example, "Start of 1st Period (10:18 PM EST)").
- **`games_with_kalshi_info_converter`**: joins the game table to the start times, converts each start time to an Eastern-time Unix timestamp, and builds each team's Kalshi ticker (`KXNBAGAME-<date><away><home>-<team>`). Quarters that start after midnight are moved to the next calendar day, but the ticker keeps the scheduled game date.
- **`fetch_kalshi_candlesticks`**: requests the 1-minute candlesticks for one market over the 5 minutes before the snapshot time and keeps the last one. Markets that don't exist return an empty table and are skipped.
- **`kalshi_price_df_generator`**: runs `fetch_kalshi_candlesticks` for every ticker and stacks the results.

In [ ]:
# ------------------------------------------------------------------------- #
######### ALL REGULAR SEASON GAMES DF #########
# ------------------------------------------------------------------------- #
def game_consolidation(season_data):
    '''
    Collapse a team box-score CSV (two rows per game) into one row per game
    Home vs away is inferred from MATCHUP: "vs." is home, "@" is away
    Parameters:
        season_data (str): Path to a team box-score file such as DATA
    Returns:
        games (df): one row per GAME_ID
    '''
    df = pd.read_csv(season_data, dtype={"GAME_ID": str})
    df = df.drop(columns=[
        "TEAM_ID", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT",
        "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "STL", "BLK", "TOV", "PF", "PLUS_MINUS"
    ])
    home = df[df["MATCHUP"].str.contains("vs.")]
    away = df[df["MATCHUP"].str.contains("@")]

    # using inner join, so games missing either side are dropped
    games = home.merge(away, on="GAME_ID", suffixes=("_HOME", "_AWAY"))
    games = games.rename(columns={"MATCHUP_AWAY": 'MATCHUP'})
    games['WINNER'] = np.where(games['WL_HOME'] == "W", games['TEAM_NAME_HOME'], games['TEAM_NAME_AWAY'])
    games = games[[
        "GAME_ID", "GAME_DATE_HOME", "MATCHUP", 
        "TEAM_ABBREVIATION_AWAY", "TEAM_NAME_AWAY", "PTS_AWAY",
        "TEAM_ABBREVIATION_HOME", "TEAM_NAME_HOME", "PTS_HOME", "WINNER"
    ]]
    return games



# ------------------------------------------------------------------------- #
######### PULL EXACT START TIME FOR EVERY GAME BY QUARTER #########
# ------------------------------------------------------------------------- #
def pull_quarter_start_times(game_ids, period):
    '''
    Pull the actual quarter start times from the play-by-play 
    endpoint for each game; "Start of 1st Period (10:18 PM EST)"
    Parameters:
        game_ids (lst of str): NBA GAME_ID values passed one at a time to PlayByPlayV3
        period (int): regulation quarters (1-4)
    Returns:
        df: one row per GAME_ID, with quarter number / start times      
    '''
    rows = []
    for gid in game_ids:
        pbp = playbyplayv3.PlayByPlayV3(game_id=gid).get_data_frames()[0]
        starts = pbp[(pbp["period"] == period) & (pbp["subType"].str.lower() == "start")]
        rows.append(starts[["gameId", "period", "description"]])
        time.sleep(REQUEST_DELAY_SECONDS)

    df = pd.concat(rows, ignore_index=True)

    # extract the start time from each row "Start of 1st Period (10:18 PM EST)""
    df["description"] = df["description"].str.split("(").str[-1].str.rstrip(")")
    
    df = df.rename(columns={
        "gameId": "GAME_ID",
        "period": "PERIOD",
        "description": "EXACT_START_TIME"
    })
    return df



# ------------------------------------------------------------------------- #
######### CREATE DF WITH KALSHI MARKET TICKERS AND TIMESTAMPS #########
# ------------------------------------------------------------------------- #
def games_with_kalshi_info_converter(df1, df2):
    '''
    Attach quarter tip time, a Unix timestamp, and Kalshi market tickers
    to the consolidated game table.
    Parameters:
        df1 (df): output from game_consolidation
        df2 (df): output from pull_quarter_start_times
    Returns:
        df: with info needed for fetching kalshi prices
    '''
    # merge the two dfs on GAME_ID using inner
    merged = pd.merge(df1, df2, on="GAME_ID", how="inner")
    merged = merged.rename(columns={
        "PERIOD": "QUARTER",
        "GAME_DATE_HOME": "GAME_DATE",
        "TEAM_ABBREVIATION_AWAY": "ABBR_AWAY",
        "TEAM_NAME_AWAY": "NAME_AWAY",
        "TEAM_ABBREVIATION_HOME": "ABBR_HOME",
        "TEAM_NAME_HOME": "NAME_HOME",
    })
    merged["ABBR_AWAY"] = merged["ABBR_AWAY"].astype(str)
    merged["ABBR_HOME"] = merged["ABBR_HOME"].astype(str)
    
    # start times are already in EST, so localize without shifting clock (don't convert to utc)
    merged["gameDateTimeEst"] = pd.to_datetime(
        merged["GAME_DATE"].astype(str) + " " + 
        merged["EXACT_START_TIME"].str.rsplit(" ", n=1).str[0],
        format="mixed"
    ).dt.tz_localize("America/New_York")

    # quarters starting after midnight belong to the next calendar day
    after_midnight = merged["EXACT_START_TIME"].str.contains("AM")
    merged.loc[after_midnight, "gameDateTimeEst"] += pd.Timedelta(days=1)

    # convert gameDateTimeEst column from object to datetieme
    merged["gameDateTimeEst"] = pd.to_datetime(merged["gameDateTimeEst"])
    # create new column for clarity using 12 hour clock
    merged["QUARTER_START(EST)"] = (merged["gameDateTimeEst"].dt.strftime("%I:%M%p").str.lstrip("0"))

    # create Kalshi market ID's for home/away teams
    # ticker date is the scheduled GAME_DATE, so quarter starts after midnight (EST) are not excluded
    scheduled = pd.to_datetime(merged["GAME_DATE"], format="mixed")
    date_part = (
        scheduled.dt.strftime("%y")
        + scheduled.dt.strftime("%b").str.upper()
        + scheduled.dt.strftime("%d")
    )
    event = "KXNBAGAME-" + date_part + merged["ABBR_AWAY"] + merged["ABBR_HOME"]
    merged["KALSHI_ID_AWAY"] = event + "-" + merged["ABBR_AWAY"]
    merged["KALSHI_ID_HOME"] = event + "-" + merged["ABBR_HOME"]

    # create a timestamp column that will be used for fetching Kalshi data later
    merged['TIMESTAMP'] = (merged['gameDateTimeEst'].astype('int64') // 1_000_000_000)

    merged = merged[[
        "GAME_ID", "QUARTER", "QUARTER_START(EST)", "GAME_DATE", "TIMESTAMP", 
        "KALSHI_ID_AWAY", "KALSHI_ID_HOME", "MATCHUP", 
        "ABBR_AWAY", "NAME_AWAY", "PTS_AWAY", 
        "ABBR_HOME", "NAME_HOME", "PTS_HOME",
        "WINNER"
    ]]
    return merged



# ------------------------------------------------------------------------- #
######### PULL KALSHI CANDLESTICK DATA FOR SINGLE GAME #########
# ------------------------------------------------------------------------- #
def fetch_kalshi_candlesticks(ticker, end_ts, period_interval=1):
    """
    Fetch historical candlesticks for one Kalshi market and keep the last one (closest
    to tip off / quarter start).
    PARAMETERS;
        - ticker (str): market ticker symbol ('KXNBAGAME-25OCT21GSWLAL-GSW')
        - end_ts (int): timestamp marking the ending of the desired period (start of the game)
        - period_interval (int): time period length of each candlestick in minutes (60=1hr candles, 1=1min candles)
    Returns (DF);
        - KALSHI_ID (str): the unique market identifier
        - TIMESTAMP (datetime): date and time of candlestick ending
        - end_period_ts (int): timestamp of the candle close
        - open_interest (str): number of contracts still open by end of the candlestick period
        - volume (str): number of contracts bought on the market during the candlestick period
        - yes_ask_close (float): ask price at the end of the candlestick period
        - yes_ask_high (float): highest ask price during the candlestick period
        - yes_ask_low (float): lowest ask price during the candlestick period
        - yes_ask_open (float): ask price at the start of the candlestick period
        - yes_bid_close (float): bid price at the end of the candlestick period
        - yes_bid_high (float): highest bid price during the candlestick period
        - yes_bid_low (float): lowest bid price during the candlestick period
        - yes_bid_open (float): bid price at the start of the candlestick period
    """
    # pull the last five 1-min candlesticks right before tipoff
    # the '+ 1' here nudges the start by one sec so we don’t pick up the previous min's candle
    start_ts = end_ts - 5 * 60 + 1

    all_candles = []
    response = requests.get(
        f"{BASE_URL}/historical/markets/{ticker}/candlesticks",
        params={'start_ts': start_ts, 'end_ts': end_ts, 'period_interval': period_interval},
        timeout=10)
    
    # error handling for if the market doesn't exist (or ticker info is wrong), or any other error
    if response.status_code == 404:
        print(f"Market {ticker} not found (404) - skipping")
        return pd.DataFrame()
    response.raise_for_status()

    # parse the JSON response and append this chunk’s candles to our list
    all_candles.extend(response.json()['candlesticks'])

    # necessary pause between requests to avoid Kalshi API rate limits
    time.sleep(REQUEST_DELAY_SECONDS)

    # flatten the nested candle dicts into a table; nested keys joined sep
    df = pd.json_normalize(all_candles, sep='_')

    # error handling
    if df.empty or 'end_period_ts' not in df.columns:
        return pd.DataFrame()
    
    # add ticker and datetime columns 
    df.insert(0, 'KALSHI_ID', ticker)
    df.insert(1, 'TIMESTAMP', pd.to_datetime(df['end_period_ts'], unit='s', utc=True))

    # keep only the last candle (one row per ticker), ensures there is at least 1 row
    df = df.sort_values("end_period_ts").tail(1).reset_index(drop=True)

    df = df.drop(columns=[
        "price_previous", 
        "price_close", "price_high", "price_low", "price_mean", "price_open",
        #"yes_ask_close", "yes_ask_high", "yes_ask_low", "yes_ask_open", 
        #"yes_bid_close", "yes_bid_high", "yes_bid_low", "yes_bid_open"
    ])
    float_cols = [
        "open_interest", "volume", 
        "yes_ask_close", "yes_ask_high", "yes_ask_low", "yes_ask_open", 
        "yes_bid_close", "yes_bid_high", "yes_bid_low", "yes_bid_open"
    ]
    df[float_cols] = df[float_cols].apply(pd.to_numeric, errors="coerce").round(4)
    return df



# ------------------------------------------------------------------------- #
######### PULL CANDLESTICK DATA FOR ALL GAMES AND COMBINE TO ONE DF #########
# ------------------------------------------------------------------------- #
def kalshi_price_df_generator(game_dict):
    '''
    Fetch the pre-tip candle for every ticker in a mapping and stack them.
    Parameters:
        game_dict (dict): including ticker (str) -> end_ts (int Unix seconds)
    Returns: 
        combined (df): concatenation of the per-ticker frames. Empty tickers are skipped.
    '''
    count = 0
    all_dfs = []
    for ticker, ts in game_dict.items():
        df = fetch_kalshi_candlesticks(ticker, ts)
        if df.empty:
            print(f"-> skipped {ticker}")
            continue
        count += 1
        #print(f"-> row {count} || {ticker} done")
        all_dfs.append(df)

    combined = pd.concat(all_dfs, ignore_index=True)
    return combined

## 3. Build the Game Table

Turns the full-game box scores into one row per game with the matchup, home and away teams, final score, and winner. This table is the base that quarter start times and Kalshi tickers are attached to.

In [27]:
games_df = game_consolidation(DATA)
games_df.head(3)

,GAME_ID,GAME_DATE_HOME,MATCHUP,TEAM_ABBREVIATION_AWAY,TEAM_NAME_AWAY,PTS_AWAY,TEAM_ABBREVIATION_HOME,TEAM_NAME_HOME,PTS_HOME,WINNER
0,0022500002,2025-10-21,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,2025-10-21,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,2025-10-22,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

## 4. Pull Quarter Start Times

Collects the list of game IDs, then pulls the start time of quarters 1–4 for every game from the NBA play-by-play endpoint. Exact start times are needed because tip-off and quarter breaks vary from game to game, and a fixed schedule time would capture prices from the wrong moment. Each pull makes one request per game and takes about 10 minutes.

In [28]:
game_ids = games_df["GAME_ID"].tolist()

In [5]:
# Takes about 10mins
q1_start_times = pull_quarter_start_times(game_ids=game_ids, period=1)
q1_start_times.head(3)

      GAME_ID  PERIOD EXACT_START_TIME
0  0022500002       1     10:18 PM EST
1  0022500001       1      7:44 PM EST
2  0022500086       1      8:14 PM EST

In [6]:
# Takes about 10mins
q2_start_times = pull_quarter_start_times(game_ids=game_ids, period=2)
q2_start_times.head(3)

      GAME_ID  PERIOD EXACT_START_TIME
0  0022500002       2     10:52 PM EST
1  0022500001       2      8:19 PM EST
2  0022500086       2      8:44 PM EST

In [7]:
# Takes about 10mins
q3_start_times = pull_quarter_start_times(game_ids=game_ids, period=3)
q3_start_times.head(3)

      GAME_ID  PERIOD EXACT_START_TIME
0  0022500002       3     11:44 PM EST
1  0022500001       3      9:07 PM EST
2  0022500086       3      9:28 PM EST

In [8]:
# Takes about 10mins
q4_start_times = pull_quarter_start_times(game_ids=game_ids, period=4)
q4_start_times.head(3)

      GAME_ID  PERIOD EXACT_START_TIME
0  0022500002       4     12:15 AM EST
1  0022500001       4      9:41 PM EST
2  0022500086       4      9:57 PM EST

## 5. Attach Kalshi Tickers and Timestamps

Loads the saved quarter start times and joins them to the game table, adding the Unix timestamp of each quarter start and the home and away Kalshi tickers. The result is one table per checkpoint, saved as the `main(...)` files. The Q1 table is the pre-game checkpoint, Q2 is End of Q1, Q3 is End of Q2, and Q4 is End of Q3.

In [29]:
q1_start_times = pd.read_csv("../data/q1_start_times.csv", dtype={"GAME_ID": str})
q1_start_with_kalshi = games_with_kalshi_info_converter(games_df, q1_start_times)
q1_start_with_kalshi.head(3)

,GAME_ID,QUARTER,QUARTER_START(EST),GAME_DATE,TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER
0,0022500002,1,10:18PM,2025-10-21,1761099480,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,1,7:44PM,2025-10-21,1761090240,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,1,8:14PM,2025-10-22,1761178440,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

In [30]:
q2_start_times = pd.read_csv("../data/q2_start_times.csv", dtype={"GAME_ID": str})
q2_start_with_kalshi = games_with_kalshi_info_converter(games_df, q2_start_times)
q2_start_with_kalshi.head(3)

,GAME_ID,QUARTER,QUARTER_START(EST),GAME_DATE,TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER
0,0022500002,2,10:52PM,2025-10-21,1761101520,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,2,8:19PM,2025-10-21,1761092340,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,2,8:44PM,2025-10-22,1761180240,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

In [31]:
q3_start_times = pd.read_csv("../data/q3_start_times.csv", dtype={"GAME_ID": str})
q3_start_with_kalshi = games_with_kalshi_info_converter(games_df, q3_start_times)
q3_start_with_kalshi.head(3)

,GAME_ID,QUARTER,QUARTER_START(EST),GAME_DATE,TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER
0,0022500002,3,11:44PM,2025-10-21,1761104640,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,3,9:07PM,2025-10-21,1761095220,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,3,9:28PM,2025-10-22,1761182880,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

In [32]:
q4_start_times = pd.read_csv("../data/q4_start_times.csv", dtype={"GAME_ID": str})
q4_start_with_kalshi = games_with_kalshi_info_converter(games_df, q4_start_times)
q4_start_with_kalshi.head(3)

,GAME_ID,QUARTER,QUARTER_START(EST),GAME_DATE,TIMESTAMP,KALSHI_ID_AWAY,KALSHI_ID_HOME,MATCHUP,ABBR_AWAY,NAME_AWAY,PTS_AWAY,ABBR_HOME,NAME_HOME,PTS_HOME,WINNER
0,0022500002,4,12:15AM,2025-10-21,1761106500,KXNBAGAME-25OCT21GSWLAL-GSW,KXNBAGAME-25OCT21GSWLAL-LAL,GSW @ LAL,GSW,Golden State Warriors,119,LAL,Los Angeles Lakers,109,Golden State Warriors
1,0022500001,4,9:41PM,2025-10-21,1761097260,KXNBAGAME-25OCT21HOUOKC-HOU,KXNBAGAME-25OCT21HOUOKC-OKC,HOU @ OKC,HOU,Houston Rockets,124,OKC,Oklahoma City Thunder,125,Oklahoma City Thunder
2,0022500086,4,9:57PM,2025-10-22,1761184620,KXNBAGAME-25OCT22WASMIL-WAS,KXNBAGAME-25OCT22WASMIL-MIL,WAS @ MIL,WAS,Washington Wizards,120,MIL,Milwaukee Bucks,133,Milwaukee Bucks

In [33]:
q1_start_with_kalshi.to_csv("../data/main(_pre-game).csv", index=False)
q2_start_with_kalshi.to_csv("../data/main(EndQ1).csv", index=False)
q3_start_with_kalshi.to_csv("../data/main(EndQ2).csv", index=False)
q4_start_with_kalshi.to_csv("../data/main(EndQ3).csv", index=False)

## 6. Pull Kalshi Prices

Maps every ticker (home and away) to its checkpoint timestamp, then fetches the last 1-minute candlestick before that time for each market. Markets that can't be found are printed and skipped. Each checkpoint takes about 20 minutes. The results are saved as the `kalshi(...)` files, which `data_prep.ipynb` uses to compute each game's normalized home-win probability from the bid/ask midpoints.

In [34]:
q1_game_dict = dict(zip(q1_start_with_kalshi['KALSHI_ID_AWAY'], q1_start_with_kalshi['TIMESTAMP'])) | dict(zip(q1_start_with_kalshi['KALSHI_ID_HOME'], q1_start_with_kalshi['TIMESTAMP']))
q2_game_dict = dict(zip(q2_start_with_kalshi['KALSHI_ID_AWAY'], q2_start_with_kalshi['TIMESTAMP'])) | dict(zip(q2_start_with_kalshi['KALSHI_ID_HOME'], q2_start_with_kalshi['TIMESTAMP']))
q3_game_dict = dict(zip(q3_start_with_kalshi['KALSHI_ID_AWAY'], q3_start_with_kalshi['TIMESTAMP'])) | dict(zip(q3_start_with_kalshi['KALSHI_ID_HOME'], q3_start_with_kalshi['TIMESTAMP']))
q4_game_dict = dict(zip(q4_start_with_kalshi['KALSHI_ID_AWAY'], q4_start_with_kalshi['TIMESTAMP'])) | dict(zip(q4_start_with_kalshi['KALSHI_ID_HOME'], q4_start_with_kalshi['TIMESTAMP']))

In [14]:
# Takes about 20mins
kalshi_q1_prices = kalshi_price_df_generator(q1_game_dict)
kalshi_q1_prices.head(3)

-> skipped KXNBAGAME-26JAN16NOPIND-NOP
-> skipped KXNBAGAME-26JAN16CLEPHI-CLE
Market KXNBAGAME-26JAN25GSWMIN-GSW not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-GSW
-> skipped KXNBAGAME-26JAN16NOPIND-IND
-> skipped KXNBAGAME-26JAN16CLEPHI-PHI
Market KXNBAGAME-26JAN25GSWMIN-MIN not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-MIN

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,yes_ask_close,yes_ask_high,yes_ask_low,yes_ask_open,yes_bid_close,yes_bid_high,yes_bid_low,yes_bid_open
0,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-22 02:18:00+00:00,1761099480,1459845.0,3457.0,0.57,0.57,0.57,0.57,0.56,0.56,0.56,0.56
1,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-21 23:44:00+00:00,1761090240,2529141.0,20834.0,0.35,0.35,0.32,0.33,0.33,0.33,0.31,0.32
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-23 00:14:00+00:00,1761178440,209143.0,2064.0,0.20,0.21,0.20,0.21,0.19,0.19,0.19,0.19

In [15]:
# Takes about 20mins
kalshi_q2_prices = kalshi_price_df_generator(q2_game_dict)
kalshi_q2_prices.head(4)

Market KXNBAGAME-26JAN25GSWMIN-GSW not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-GSW
Market KXNBAGAME-26JAN25GSWMIN-MIN not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-MIN

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,yes_ask_close,yes_ask_high,yes_ask_low,yes_ask_open,yes_bid_close,yes_bid_high,yes_bid_low,yes_bid_open
0,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-22 02:52:00+00:00,1761101520,1757902.0,179.0,0.68,0.68,0.68,0.68,0.67,0.67,0.67,0.67
1,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-22 00:19:00+00:00,1761092340,3074575.0,10541.0,0.39,0.39,0.38,0.39,0.38,0.38,0.37,0.37
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-23 00:44:00+00:00,1761180240,288430.0,1418.0,0.04,0.05,0.04,0.05,0.03,0.04,0.03,0.04
3,KXNBAGAME-25OCT22CLENYK-CLE,2025-10-22 23:43:00+00:00,1761176580,1946337.0,7521.0,0.37,0.38,0.37,0.38,0.36,0.37,0.36,0.37

In [35]:
# Takes about 20mins
kalshi_q3_prices = kalshi_price_df_generator(q3_game_dict)
kalshi_q3_prices.head(4)

Market KXNBAGAME-26JAN25GSWMIN-GSW not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-GSW
Market KXNBAGAME-26JAN25GSWMIN-MIN not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-MIN

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,yes_ask_close,yes_ask_high,yes_ask_low,yes_ask_open,yes_bid_close,yes_bid_high,yes_bid_low,yes_bid_open
0,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-22 03:44:00+00:00,1761104640,3381257.0,16731.0,0.58,0.58,0.58,0.58,0.57,0.57,0.57,0.57
1,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-22 01:07:00+00:00,1761095220,3428711.0,13528.0,0.48,0.48,0.48,0.48,0.47,0.47,0.47,0.47
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-23 01:28:00+00:00,1761182880,347042.0,2157.0,0.03,0.03,0.03,0.03,0.02,0.02,0.02,0.02
3,KXNBAGAME-25OCT22CLENYK-CLE,2025-10-23 00:30:00+00:00,1761179400,2393489.0,4843.0,0.21,0.21,0.21,0.21,0.20,0.20,0.20,0.20

In [37]:
# Takes about 20mins
kalshi_q4_prices = kalshi_price_df_generator(q4_game_dict)
kalshi_q4_prices.head(4)

-> skipped KXNBAGAME-25NOV15DENMIN-DEN
Market KXNBAGAME-26JAN25GSWMIN-GSW not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-GSW
-> skipped KXNBAGAME-26MAR08CHAPHX-CHA
-> skipped KXNBAGAME-25NOV15DENMIN-MIN
Market KXNBAGAME-26JAN25GSWMIN-MIN not found (404) - skipping
-> skipped KXNBAGAME-26JAN25GSWMIN-MIN
-> skipped KXNBAGAME-26MAR08CHAPHX-PHX

,KALSHI_ID,TIMESTAMP,end_period_ts,open_interest,volume,yes_ask_close,yes_ask_high,yes_ask_low,yes_ask_open,yes_bid_close,yes_bid_high,yes_bid_low,yes_bid_open
0,KXNBAGAME-25OCT21GSWLAL-GSW,2025-10-22 04:15:00+00:00,1761106500,4045969.0,30131.0,0.86,0.87,0.86,0.87,0.85,0.86,0.85,0.86
1,KXNBAGAME-25OCT21HOUOKC-HOU,2025-10-22 01:41:00+00:00,1761097260,3690655.0,14269.0,0.54,0.54,0.53,0.53,0.52,0.52,0.51,0.52
2,KXNBAGAME-25OCT22WASMIL-WAS,2025-10-23 01:57:00+00:00,1761184620,527397.0,2478.0,0.06,0.06,0.06,0.06,0.03,0.05,0.03,0.05
3,KXNBAGAME-25OCT22CLENYK-CLE,2025-10-23 01:08:00+00:00,1761181680,2228605.0,14558.0,0.52,0.54,0.52,0.54,0.50,0.52,0.50,0.52

In [ ]:
kalshi_q1_prices.to_csv("../data/kalshi(_pre-game).csv", index=False)
kalshi_q2_prices.to_csv("../data/kalshi(EndQ1).csv", index=False)
kalshi_q3_prices.to_csv("../data/kalshi(EndQ2).csv", index=False)
kalshi_q4_prices.to_csv("../data/kalshi(EndQ3).csv", index=False)